[package]
name = "MP3toAT"
version = "0.1.0"
edition = "2021"

[dependencies]
hound = "3.5.1"
clap = { version = "4.5.23", features = ["derive"] }
base64 = "0.22.1"

[[bin]]
name = "MP3toAT"
path = "src/MP3toAT.rs"
